matrix:
  include:
    - language: go
      os:
        - linux
        - osx
      go:
        - 1.9.x
        - 1.10.x
        - 1.11.x
      script:
        - pwd
        - go test ./pkg/utils/

notifications:
  email:
    - 792400644@qq.com